---
image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

cache:
  key: nhh-argos-front
  paths:
    - node_modules/
    - $TARGET_DIR_ON_LOCAL

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  only:
    - "master"
    - "dev"
  image: node:12-stretch
  environment: Production
  variables:
    NODE_OPTIONS: --max-old-space-size=4096
  script:
    - npm cache clean --force
    - npm install
    - npm run build
  artifacts:
    name: "stat-_$CI_COMMIT_REF_NAME"
    paths:
      - dist/

  tags: [build]
    
Test:
  stage: test
  only:
    - "master"
    - "dev"
  script:
    - echo "Place for testing project"
  tags: [test]

Deploy to Prod Server:
  stage: deploy
  only:
    - "master"
  when: manual
  image: gitlab.mintrud.local:5005/argos/nhh-argos-front/ubuntu_rsync:20.04
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_USER_KEY_PROD")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    #- echo "${SSH_HOST_KEY_PROD}" > ~/.ssh/known_hosts
    - ssh-keyscan -H $DEPLOY_SERVER_PROD >> ~/.ssh/known_hosts
  script:
    - ls $TARGET_DIR_ON_LOCAL
    - rsync -arv --cvs-exclude --exclude="robots.txt" --exclude=".well-known" --delete $TARGET_DIR_ON_LOCAL $SSH_USER_PROD@$DEPLOY_SERVER_PROD:$TARGET_DIR_ON_HOST_PROD
  tags: [deploy]
